version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      echo Installing frontend dependencies...
      cd client
      npm install

  build:
    commands:
      echo Building the React app...
      cd client
      npm run build

  post_build:
    commands:
      echo Zipping build folder for S3 deployment...
      cd client
      zip -r build.zip build  # Create build.zip from the build folder
      echo Uploading build.zip to S3...
      aws s3 cp build.zip s3://sports-react/frontend/build.zip  # Upload to S3

artifacts:
  files:
    - client/build.zip  # This will collect build.zip created in post_build phase
